version: '3.3'

services:

  frontend:
    image: plone/ploneconf-frontend:2022
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - public
      - ploneconf2022
    deploy:
      replicas: 2
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=public
        # Service
        - traefik.http.services.ploneconf2022-frontend.loadbalancer.server.port=3000
        # Router
        - traefik.http.routers.ploneconf2022-frontend.rule=Host(`2022.ploneconf.org`)
        - traefik.http.routers.ploneconf2022-frontend.entrypoints=https
        - traefik.http.routers.ploneconf2022-frontend.tls=true
        - traefik.http.routers.ploneconf2022-frontend.tls.certresolver=le
        - traefik.http.routers.ploneconf2022-frontend.service=ploneconf2022-frontend
        - traefik.http.routers.ploneconf2022-frontend.middlewares=gzip

  backend:
    image: plone/ploneconf-backend:2022
    environment:
      RELSTORAGE_DSN: "dbname='${DB_NAME:-ploneconf2022}' user='${DB_USER:-ploneconf2022}' host='${DB_HOST:-db}' password='${DB_PASSWORD:-ploneconf2022}'"
    networks:
      - public
      - ploneconf2022
    deploy:
      replicas: 2
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=public
        # Service
        - traefik.http.services.ploneconf2022-backend.loadbalancer.server.port=8080
        # Middleware
        - "traefik.http.middlewares.ploneconf2022-vhm.replacepathregex.regex=^/\\+\\+api\\+\\+($$|/.*)"
        - "traefik.http.middlewares.ploneconf2022-vhm.replacepathregex.replacement=/VirtualHostBase/https/2022.ploneconf.org/Plone/++api++/VirtualHostRoot/$$1"
        # Router
        - traefik.http.routers.ploneconf2022-backend.rule=Host(`2022.ploneconf.org`) && (PathPrefix(`/++api++`))
        - traefik.http.routers.ploneconf2022-backend.entrypoints=https
        - traefik.http.routers.ploneconf2022-backend.tls=true
        - traefik.http.routers.ploneconf2022-backend.service=ploneconf2022-backend
        - traefik.http.routers.ploneconf2022-backend.middlewares=gzip,ploneconf2022-vhm

networks:
  public:
    external: true
    driver: overlay
  ploneconf2022:
    driver: overlay
