name: Deploy 2022.ploneconf.org

on:
  workflow_run:
    workflows: [Acceptance Tests]
    types:
      - completed
    branches:
      - "2022"

jobs:

  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: ploneconf.org
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to 2022.ploneconf.org
        uses: kitconcept/docker-stack-deploy@v1.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_private_key: ${{ secrets.DEPLOY_SSH }}
          stack_file: "devops/stacks/2022.ploneconf.org.yml"
          stack_name: "plone"
          deploy_timeout: 480

  report-skipped:
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Report the reason for skipping a deploy
        run: echo "$GITHUB_CONTEXT"
