name: Test the frontend code
on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/test-frontend.yml"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: frontend
          push: ${{ github.ref == 'refs/heads/2021' }}
          tags: plone/ploneconf-frontend:2021

  deploy:
    if: ${{ github.ref == 'refs/heads/2021' }}
    needs:
      - docker
    runs-on: ubuntu-latest
    environment: "2021.ploneconf.org"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to plone.org
        uses: kitconcept/docker-stack-deploy@v1.2.0
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_private_key: ${{ secrets.DEPLOY_SSH }}
          stack_file: "devops/stacks/2021.ploneconf.org.yml"
          stack_name: "ploneconf2021"
          env_file: ${{ secrets.ENV_FILE }}
          deploy_timeout: 480
